# Generated by Django 3.1.5 on 2021-02-03 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello_world', '0002_auto_20210203_0046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='student',
        ),
    ]
